version: '1.0'

stages:
  - git-clone
  - unit-test
  - build
  - push
steps:
  main_clone:
    title: Cloning main repository...
    type: git-clone
    stage: git-clone
    repo: '${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}'
    revision: '${{CF_REVISION}}'
    git: github

  MyUnitTests:
    title: Unit test
    stage: unit-test
    image: node:8.16
    commands:
      - yarn install
      - yarn test
    environment:
      - CI=true

  MyAppDockerImage:
    title: Building Docker Image
    type: build
    stage: build
    image_name: react-sample-app
    working_directory: ./
    tag: '${{CF_BRANCH}}'
    dockerfile: Dockerfile
    disable_push: true

  MyPushStep:
    title: Pushing to Docker Registry
    type: push
    stage: push
    tag: '${{CF_BRANCH}}'
    candidate: '${{MyAppDockerImage}}'
    image_name: ariesmcrae/react-sample-app
    registry: github-container-registry
